language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.8-dev"
 - "nightly"
script: ./runtest.py && cd sample-data && ./test.sh

# Adapted from the code written by Walter Purcaro and shared on at travis-ci#9929
jobs:
  include:
    - stage: test
      os: osx
      language: sh
      env:
        - TOXENV=py3
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1
      before_cache:
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        directories:
          - "$HOME/Library/Caches/pip"
      addons:
        homebrew:
          update: false
          packages: python3
      before_install:
        - python3 -m pip install --upgrade virtualenv
        - virtualenv -p python3 --system-site-packages "$HOME/venv"
        - source "$HOME/venv/bin/activate"
      script: ./runtest.py && cd sample-data && ./test.sh
